Repository artichoke/raw-parts, pull requests merged in 2021-12, with the labels that each got.

#17 Remove bounds on T for Debug, PartialEq and Hash impls
  .gitignore
  src/lib.rs
Labels: A-raw-parts

#18 Update .gitignore
  .gitignore
Labels: C-quality

#19 Update README.md
  README.md
Labels: C-docs

#20 Bump version to v1.1.0
  Cargo.toml
  README.md
  src/lib.rs
Labels: A-release

#21 Add documentation and homepage links to Cargo.toml
  Cargo.toml
  src/lib.rs
Labels: A-packaging, C-quality
